run:
    cargo run

runr:
    cargo run --release

build:
    cargo build

buildr:
    cargo build --release

clip:
    cargo clippy --fix --allow-dirty --allow-staged --all-targets

fix:
    cargo fmt
    cargo clippy --fix --allow-dirty --allow-staged --all-targets
    cargo fmt

upgrade:
    cargo update
