name: szyszka # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Szyszka - fast file renamer written in Rust # 79 char long summary
description: |
  Szyszka is very fast file renamer written in Rust.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  user-part:
    source: .
    plugin: rust
    build-packages: [cargo, rustc]
  szyszka:
    plugin: rust
    source: https://github.com/qarmin/szyszka.git
    build-packages:
      - curl
      - gcc
      - git

apps:
  szyszka:
    command: bin/szyszka
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - udisks2
