name: szyszka # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Szyszka - fast file renamer written in Rust # 79 char long summary
description: |
  Szyszka is very fast file renamer written in Rust.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo

license: MIT
website: https://github.com/qarmin/szyszka
issues: https://github.com/qarmin/szyszka/issues
donation: https://github.com/sponsors/qarmin

parts:
  rust-deps:
    plugin: nil
    override-pull: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.69.0
  czkawka:
    plugin: rust
    after: [ rust-deps ]
    source: https://github.com/qarmin/szyszka.git
    build-packages:
      - curl
      - gcc
      - git

apps:
  szyszka:
    command: bin/szyszka
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - udisks2
