name: 🐧 Linux
on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: linux-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-${{github.ref}}-${{github.sha}}

      - name: Install Gtk, Mingw, unzip, zip and wget
        run: sudo apt update; sudo apt install libgtk-3-dev -y

      - name: Build Debug
        run: cargo build
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"
        if: ${{ matrix.type == 'debug'}}

      - name: Build Release
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"
        if: ${{ matrix.type == 'release'}}

      - name: Store Linux
        uses: actions/upload-artifact@v2
        with:
          name: szyszka-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/szyszka
        if: ${{ matrix.type == 'release' }}

  linux-appimage:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ release ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: linux-appimage-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-appimage-${{github.ref}}-${{github.sha}}

      - name: Install Gtk,
        run: sudo apt update; sudo apt install libgtk-3-dev librsvg2-dev wget -y

      - name: Build Release
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

      - name: Download appimage dependiences
        run: |
          wget -c "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"
          wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          chmod +x linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-x86_64.AppImage
          mkdir -p AppDir/usr/bin
          cp target/release/szyszka AppDir/usr/bin
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin gtk --output appimage --icon-file data/icons/com.github.qarmin.szyszka.svg --desktop-file data/com.github.qarmin.szyszka.desktop

      - name: Store Linux Appimage
        uses: actions/upload-artifact@v2
        with:
          name: szyszka-appimage-${{ runner.os }}-${{ matrix.toolchain }}
          path: Szyszka*.AppImage
