name: 🐧 Linux
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup rust version
        run: rustup default 1.94.1

      - name: Build Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "VERS=release" >> $GITHUB_ENV

          cargo build --release
          mv target/release/szyszka linux_szyszka_x86_64

      - name: Build Debug
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          sed -i 's/^\(\[profile\.dev\.package.*\)/#\1/' Cargo.toml
          sed -i 's|^opt-level = 3 # OPT PACKAGES|#opt-level = 3 # OPT PACKAGES|' Cargo.toml

          echo "VERS=debug" >> $GITHUB_ENV

          cargo build --profile fastci
          mv target/fastci/szyszka linux_szyszka_x86_64

      - name: Store
        uses: actions/upload-artifact@v6
        with:
          name: szyszka-${{ runner.os }}-${{ env.VERS }}
          path: linux_szyszka_x86_64
