name: 🐧 Linux
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-default:
    strategy:
      matrix:
        toolchain: [ stable, 1.70.0 ]
        type: [ release ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust version
        run: rustup default ${{ matrix.toolchain }}

      - name: Install basic libraries
        run: sudo apt-get update; sudo apt install libgtk-4-dev -y

      - name: Build Release
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
        if: ${{ matrix.type == 'release' }}

      - name: Store Linux GUI
        uses: actions/upload-artifact@v3
        with:
          name: szyszka-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/szyszka
        if: ${{ matrix.type == 'release' }}

  linux-tests:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ debug ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust version
        run: rustup default ${{ matrix.toolchain }}

      - name: Install Dependencies
        run: sudo apt-get update; sudo apt install libgtk-4-dev librsvg2-dev wget fuse libfuse2 -y xvfb

      - name: Test
        run: xvfb-run cargo test
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"