name: 🏁 Windows
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup rust version
        run: rustup default 1.94.1

      - name: Build Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "VERS=release" >> $env:GITHUB_ENV

          cargo build --release
          mv target/release/szyszka.exe windows_szyszka.exe

      - name: Build Debug
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          (Get-Content Cargo.toml) -replace '^\[profile\.dev\.package','#[profile.dev.package' -replace '^opt-level = 3 # OPT PACKAGES','#opt-level = 3 # OPT PACKAGES' | Set-Content Cargo.toml

          echo "VERS=debug" >> $env:GITHUB_ENV

          cargo build --profile fastci
          mv target/fastci/szyszka.exe windows_szyszka.exe

      - name: Store
        uses: actions/upload-artifact@v6
        with:
          name: szyszka-${{ runner.os }}-${{ env.VERS }}
          path: windows_szyszka.exe
